### ISSUE TITLE
dataset preprocess

### ISSUE THREAD

**Issue by Harry-hash** [jiachangliu/KATEGPT3#1]
Hi, will you release the codes to preprocess datasets, e.g., Natural Questions, and reproduce your results? Thanks a lot!

**Comment by jiachangliu** [comment]
Hello @Harry-hash , I have added a new Section 4 in the README page. In Section 4, you can find links to all preprocessed datasets and computed kNN .dat files. With these files, if you have a GPT3 API, you should be able to reproduce all results shown in the paper. Let me know if you have additional questions.
